package com.hszsd.webpay.dao;

import com.hszsd.webpay.condition.AccountQuickBankCondition;
import com.hszsd.webpay.po.AccountQuickBankPO;
import com.hszsd.webpay.web.dto.AccountQuickBankDTO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AccountQuickBankDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_QUICK_BANK
     *
     * @mbggenerated
     */
    int countByCondition(AccountQuickBankCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_QUICK_BANK
     *
     * @mbggenerated
     */
    int deleteByCondition(AccountQuickBankCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_QUICK_BANK
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_QUICK_BANK
     *
     * @mbggenerated
     */
    int insert(AccountQuickBankPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_QUICK_BANK
     *
     * @mbggenerated
     */
    int insertSelective(AccountQuickBankPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_QUICK_BANK
     *
     * @mbggenerated
     */
    List<AccountQuickBankDTO> selectByCondition(AccountQuickBankCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_QUICK_BANK
     *
     * @mbggenerated
     */
    AccountQuickBankDTO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_QUICK_BANK
     *
     * @mbggenerated
     */
    int updateByConditionSelective(@Param("record") AccountQuickBankPO record, @Param("condition") AccountQuickBankCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_QUICK_BANK
     *
     * @mbggenerated
     */
    int updateByCondition(@Param("record") AccountQuickBankPO record, @Param("condition") AccountQuickBankCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_QUICK_BANK
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AccountQuickBankPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_QUICK_BANK
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AccountQuickBankPO record);
}