package com.hszsd.webpay.dao;

import com.hszsd.webpay.condition.AccountBankCondition;
import com.hszsd.webpay.po.AccountBankPO;
import com.hszsd.webpay.web.dto.AccountBankDTO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AccountBankDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_BANK
     *
     * @mbggenerated
     */
    int countByCondition(AccountBankCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_BANK
     *
     * @mbggenerated
     */
    int deleteByCondition(AccountBankCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_BANK
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_BANK
     *
     * @mbggenerated
     */
    int insert(AccountBankPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_BANK
     *
     * @mbggenerated
     */
    int insertSelective(AccountBankPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_BANK
     *
     * @mbggenerated
     */
    List<AccountBankDTO> selectByCondition(AccountBankCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_BANK
     *
     * @mbggenerated
     */
    AccountBankDTO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_BANK
     *
     * @mbggenerated
     */
    int updateByConditionSelective(@Param("record") AccountBankPO record, @Param("condition") AccountBankCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_BANK
     *
     * @mbggenerated
     */
    int updateByCondition(@Param("record") AccountBankPO record, @Param("condition") AccountBankCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_BANK
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AccountBankPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_ACCOUNT_BANK
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AccountBankPO record);
}