package com.hszsd.webpay.dao;

import com.hszsd.webpay.condition.BankInfoCondition;
import com.hszsd.webpay.po.BankInfoPO;
import com.hszsd.webpay.web.dto.BankInfoDTO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BankInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    int countByCondition(BankInfoCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    int deleteByCondition(BankInfoCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(long bankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    int insert(BankInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    int insertSelective(BankInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    List<BankInfoDTO> selectByCondition(BankInfoCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    BankInfoDTO selectByPrimaryKey(long bankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    int updateByConditionSelective(@Param("record") BankInfoPO record, @Param("condition") BankInfoCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    int updateByCondition(@Param("record") BankInfoPO record, @Param("condition") BankInfoCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BankInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BankInfoPO record);
}