package com.hszsd.webpay.dao;

import com.hszsd.webpay.condition.PaymentInterfaceCondition;
import com.hszsd.webpay.po.PaymentInterfacePO;
import com.hszsd.webpay.web.dto.PaymentInterfaceDTO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PaymentInterfaceDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_PAYMENT_INTERFACE
     *
     * @mbggenerated
     */
    int countByCondition(PaymentInterfaceCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_PAYMENT_INTERFACE
     *
     * @mbggenerated
     */
    int deleteByCondition(PaymentInterfaceCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_PAYMENT_INTERFACE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(long interfaceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_PAYMENT_INTERFACE
     *
     * @mbggenerated
     */
    int insert(PaymentInterfacePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_PAYMENT_INTERFACE
     *
     * @mbggenerated
     */
    int insertSelective(PaymentInterfacePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_PAYMENT_INTERFACE
     *
     * @mbggenerated
     */
    List<PaymentInterfaceDTO> selectByCondition(PaymentInterfaceCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_PAYMENT_INTERFACE
     *
     * @mbggenerated
     */
    PaymentInterfaceDTO selectByPrimaryKey(long interfaceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_PAYMENT_INTERFACE
     *
     * @mbggenerated
     */
    int updateByConditionSelective(@Param("record") PaymentInterfacePO record, @Param("condition") PaymentInterfaceCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_PAYMENT_INTERFACE
     *
     * @mbggenerated
     */
    int updateByCondition(@Param("record") PaymentInterfacePO record, @Param("condition") PaymentInterfaceCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_PAYMENT_INTERFACE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PaymentInterfacePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_PAYMENT_INTERFACE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PaymentInterfacePO record);
}