package com.hszsd.webpay.dao;

import com.hszsd.webpay.condition.TradeRecordCondition;
import com.hszsd.webpay.po.TradeRecordPO;
import com.hszsd.webpay.web.dto.TradeRecordDTO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TradeRecordDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_RECORD_TMP
     *
     * @mbggenerated
     */
    int countByCondition(TradeRecordCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_RECORD_TMP
     *
     * @mbggenerated
     */
    int deleteByCondition(TradeRecordCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_RECORD_TMP
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String transId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_RECORD_TMP
     *
     * @mbggenerated
     */
    int insert(TradeRecordPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_RECORD_TMP
     *
     * @mbggenerated
     */
    int insertSelective(TradeRecordPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_RECORD_TMP
     *
     * @mbggenerated
     */
    List<TradeRecordDTO> selectByCondition(TradeRecordCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_RECORD_TMP
     *
     * @mbggenerated
     */
    TradeRecordDTO selectByPrimaryKey(String transId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_RECORD_TMP
     *
     * @mbggenerated
     */
    int updateByConditionSelective(@Param("record") TradeRecordPO record, @Param("condition") TradeRecordCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_RECORD_TMP
     *
     * @mbggenerated
     */
    int updateByCondition(@Param("record") TradeRecordPO record, @Param("condition") TradeRecordCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_RECORD_TMP
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradeRecordPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_RECORD_TMP
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradeRecordPO record);
}