package com.hszsd.webpay.condition;

import java.util.ArrayList;
import java.util.List;

public class OnlineBankCondition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HSPRD.TB_ONLINE_BANK_034
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HSPRD.TB_ONLINE_BANK_034
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HSPRD.TB_ONLINE_BANK_034
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPRD.TB_ONLINE_BANK_034
     *
     * @mbggenerated
     */
    public OnlineBankCondition() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPRD.TB_ONLINE_BANK_034
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPRD.TB_ONLINE_BANK_034
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPRD.TB_ONLINE_BANK_034
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPRD.TB_ONLINE_BANK_034
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPRD.TB_ONLINE_BANK_034
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPRD.TB_ONLINE_BANK_034
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPRD.TB_ONLINE_BANK_034
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPRD.TB_ONLINE_BANK_034
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPRD.TB_ONLINE_BANK_034
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPRD.TB_ONLINE_BANK_034
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HSPRD.TB_ONLINE_BANK_034
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(long value1, long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(long value1, long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNull() {
            addCriterion("BANK_NAME is null");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNotNull() {
            addCriterion("BANK_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andBankNameEqualTo(String value) {
            addCriterion("BANK_NAME =", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotEqualTo(String value) {
            addCriterion("BANK_NAME <>", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThan(String value) {
            addCriterion("BANK_NAME >", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_NAME >=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThan(String value) {
            addCriterion("BANK_NAME <", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThanOrEqualTo(String value) {
            addCriterion("BANK_NAME <=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLike(String value) {
            addCriterion("BANK_NAME like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotLike(String value) {
            addCriterion("BANK_NAME not like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameIn(List<String> values) {
            addCriterion("BANK_NAME in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotIn(List<String> values) {
            addCriterion("BANK_NAME not in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameBetween(String value1, String value2) {
            addCriterion("BANK_NAME between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotBetween(String value1, String value2) {
            addCriterion("BANK_NAME not between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankLogoIsNull() {
            addCriterion("BANK_LOGO is null");
            return (Criteria) this;
        }

        public Criteria andBankLogoIsNotNull() {
            addCriterion("BANK_LOGO is not null");
            return (Criteria) this;
        }

        public Criteria andBankLogoEqualTo(String value) {
            addCriterion("BANK_LOGO =", value, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoNotEqualTo(String value) {
            addCriterion("BANK_LOGO <>", value, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoGreaterThan(String value) {
            addCriterion("BANK_LOGO >", value, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_LOGO >=", value, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoLessThan(String value) {
            addCriterion("BANK_LOGO <", value, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoLessThanOrEqualTo(String value) {
            addCriterion("BANK_LOGO <=", value, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoLike(String value) {
            addCriterion("BANK_LOGO like", value, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoNotLike(String value) {
            addCriterion("BANK_LOGO not like", value, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoIn(List<String> values) {
            addCriterion("BANK_LOGO in", values, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoNotIn(List<String> values) {
            addCriterion("BANK_LOGO not in", values, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoBetween(String value1, String value2) {
            addCriterion("BANK_LOGO between", value1, value2, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoNotBetween(String value1, String value2) {
            addCriterion("BANK_LOGO not between", value1, value2, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankValueIsNull() {
            addCriterion("BANK_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andBankValueIsNotNull() {
            addCriterion("BANK_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andBankValueEqualTo(String value) {
            addCriterion("BANK_VALUE =", value, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueNotEqualTo(String value) {
            addCriterion("BANK_VALUE <>", value, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueGreaterThan(String value) {
            addCriterion("BANK_VALUE >", value, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_VALUE >=", value, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueLessThan(String value) {
            addCriterion("BANK_VALUE <", value, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueLessThanOrEqualTo(String value) {
            addCriterion("BANK_VALUE <=", value, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueLike(String value) {
            addCriterion("BANK_VALUE like", value, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueNotLike(String value) {
            addCriterion("BANK_VALUE not like", value, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueIn(List<String> values) {
            addCriterion("BANK_VALUE in", values, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueNotIn(List<String> values) {
            addCriterion("BANK_VALUE not in", values, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueBetween(String value1, String value2) {
            addCriterion("BANK_VALUE between", value1, value2, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueNotBetween(String value1, String value2) {
            addCriterion("BANK_VALUE not between", value1, value2, "bankValue");
            return (Criteria) this;
        }

        public Criteria andPaymentInterfaceIdIsNull() {
            addCriterion("PAYMENT_INTERFACE_ID is null");
            return (Criteria) this;
        }

        public Criteria andPaymentInterfaceIdIsNotNull() {
            addCriterion("PAYMENT_INTERFACE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentInterfaceIdEqualTo(String value) {
            addCriterion("PAYMENT_INTERFACE_ID =", value, "paymentInterfaceId");
            return (Criteria) this;
        }

        public Criteria andPaymentInterfaceIdNotEqualTo(String value) {
            addCriterion("PAYMENT_INTERFACE_ID <>", value, "paymentInterfaceId");
            return (Criteria) this;
        }

        public Criteria andPaymentInterfaceIdGreaterThan(String value) {
            addCriterion("PAYMENT_INTERFACE_ID >", value, "paymentInterfaceId");
            return (Criteria) this;
        }

        public Criteria andPaymentInterfaceIdGreaterThanOrEqualTo(String value) {
            addCriterion("PAYMENT_INTERFACE_ID >=", value, "paymentInterfaceId");
            return (Criteria) this;
        }

        public Criteria andPaymentInterfaceIdLessThan(String value) {
            addCriterion("PAYMENT_INTERFACE_ID <", value, "paymentInterfaceId");
            return (Criteria) this;
        }

        public Criteria andPaymentInterfaceIdLessThanOrEqualTo(String value) {
            addCriterion("PAYMENT_INTERFACE_ID <=", value, "paymentInterfaceId");
            return (Criteria) this;
        }

        public Criteria andPaymentInterfaceIdLike(String value) {
            addCriterion("PAYMENT_INTERFACE_ID like", value, "paymentInterfaceId");
            return (Criteria) this;
        }

        public Criteria andPaymentInterfaceIdNotLike(String value) {
            addCriterion("PAYMENT_INTERFACE_ID not like", value, "paymentInterfaceId");
            return (Criteria) this;
        }

        public Criteria andPaymentInterfaceIdIn(List<String> values) {
            addCriterion("PAYMENT_INTERFACE_ID in", values, "paymentInterfaceId");
            return (Criteria) this;
        }

        public Criteria andPaymentInterfaceIdNotIn(List<String> values) {
            addCriterion("PAYMENT_INTERFACE_ID not in", values, "paymentInterfaceId");
            return (Criteria) this;
        }

        public Criteria andPaymentInterfaceIdBetween(String value1, String value2) {
            addCriterion("PAYMENT_INTERFACE_ID between", value1, value2, "paymentInterfaceId");
            return (Criteria) this;
        }

        public Criteria andPaymentInterfaceIdNotBetween(String value1, String value2) {
            addCriterion("PAYMENT_INTERFACE_ID not between", value1, value2, "paymentInterfaceId");
            return (Criteria) this;
        }

        public Criteria andIsEnableIsNull() {
            addCriterion("IS_ENABLE is null");
            return (Criteria) this;
        }

        public Criteria andIsEnableIsNotNull() {
            addCriterion("IS_ENABLE is not null");
            return (Criteria) this;
        }

        public Criteria andIsEnableEqualTo(int value) {
            addCriterion("IS_ENABLE =", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotEqualTo(int value) {
            addCriterion("IS_ENABLE <>", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableGreaterThan(int value) {
            addCriterion("IS_ENABLE >", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableGreaterThanOrEqualTo(int value) {
            addCriterion("IS_ENABLE >=", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableLessThan(int value) {
            addCriterion("IS_ENABLE <", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableLessThanOrEqualTo(int value) {
            addCriterion("IS_ENABLE <=", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableIn(List<Integer> values) {
            addCriterion("IS_ENABLE in", values, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotIn(List<Integer> values) {
            addCriterion("IS_ENABLE not in", values, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableBetween(int value1, int value2) {
            addCriterion("IS_ENABLE between", value1, value2, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotBetween(int value1, int value2) {
            addCriterion("IS_ENABLE not between", value1, value2, "isEnable");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HSPRD.TB_ONLINE_BANK_034
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HSPRD.TB_ONLINE_BANK_034
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}