package com.hszsd.webpay.po;

import java.math.BigDecimal;

public class PaymentInterfacePO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_PAYMENT_INTERFACE_035.ID
     *
     * @mbggenerated
     */
    private long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_PAYMENT_INTERFACE_035.MERCHANT_ID
     *
     * @mbggenerated
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_PAYMENT_INTERFACE_035.MERCHANT_KEY
     *
     * @mbggenerated
     */
    private String merchantKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_PAYMENT_INTERFACE_035.RECHARGE_FEE
     *
     * @mbggenerated
     */
    private BigDecimal rechargeFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_PAYMENT_INTERFACE_035.PAY_URL
     *
     * @mbggenerated
     */
    private String payUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_PAYMENT_INTERFACE_035.RETURN_URL
     *
     * @mbggenerated
     */
    private String returnUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_PAYMENT_INTERFACE_035.NOTICE_URL
     *
     * @mbggenerated
     */
    private String noticeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_PAYMENT_INTERFACE_035.IS_ENABLE_SINGLE
     *
     * @mbggenerated
     */
    private int isEnableSingle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_PAYMENT_INTERFACE_035.CHARTSET
     *
     * @mbggenerated
     */
    private String chartset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_PAYMENT_INTERFACE_035.INTERFACE_INTO_ACCOUNT
     *
     * @mbggenerated
     */
    private String interfaceIntoAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_PAYMENT_INTERFACE_035.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_PAYMENT_INTERFACE_035.INTERFACE_VALUE
     *
     * @mbggenerated
     */
    private String interfaceValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_PAYMENT_INTERFACE_035.IS_ENABLE_UNSINGLE
     *
     * @mbggenerated
     */
    private int isEnableUnsingle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_PAYMENT_INTERFACE_035.SIGN_TYPE
     *
     * @mbggenerated
     */
    private String signType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_PAYMENT_INTERFACE_035.PAY_STYLE
     *
     * @mbggenerated
     */
    private String payStyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_PAYMENT_INTERFACE_035.SELLER_EMAIL
     *
     * @mbggenerated
     */
    private String sellerEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_PAYMENT_INTERFACE_035.TRANSPORT
     *
     * @mbggenerated
     */
    private String transport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_PAYMENT_INTERFACE_035.ORDER_DESCRIPTION
     *
     * @mbggenerated
     */
    private String orderDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_PAYMENT_INTERFACE_035.ORDER_BY
     *
     * @mbggenerated
     */
    private long orderBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_PAYMENT_INTERFACE_035.LOGO_URL
     *
     * @mbggenerated
     */
    private String logoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_PAYMENT_INTERFACE_035.STATE
     *
     * @mbggenerated
     */
    private int state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.ID
     *
     * @return the value of HSPRD.TB_PAYMENT_INTERFACE_035.ID
     *
     * @mbggenerated
     */
    public long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.ID
     *
     * @param id the value for HSPRD.TB_PAYMENT_INTERFACE_035.ID
     *
     * @mbggenerated
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.MERCHANT_ID
     *
     * @return the value of HSPRD.TB_PAYMENT_INTERFACE_035.MERCHANT_ID
     *
     * @mbggenerated
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.MERCHANT_ID
     *
     * @param merchantId the value for HSPRD.TB_PAYMENT_INTERFACE_035.MERCHANT_ID
     *
     * @mbggenerated
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.MERCHANT_KEY
     *
     * @return the value of HSPRD.TB_PAYMENT_INTERFACE_035.MERCHANT_KEY
     *
     * @mbggenerated
     */
    public String getMerchantKey() {
        return merchantKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.MERCHANT_KEY
     *
     * @param merchantKey the value for HSPRD.TB_PAYMENT_INTERFACE_035.MERCHANT_KEY
     *
     * @mbggenerated
     */
    public void setMerchantKey(String merchantKey) {
        this.merchantKey = merchantKey == null ? null : merchantKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.RECHARGE_FEE
     *
     * @return the value of HSPRD.TB_PAYMENT_INTERFACE_035.RECHARGE_FEE
     *
     * @mbggenerated
     */
    public BigDecimal getRechargeFee() {
        return rechargeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.RECHARGE_FEE
     *
     * @param rechargeFee the value for HSPRD.TB_PAYMENT_INTERFACE_035.RECHARGE_FEE
     *
     * @mbggenerated
     */
    public void setRechargeFee(BigDecimal rechargeFee) {
        this.rechargeFee = rechargeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.PAY_URL
     *
     * @return the value of HSPRD.TB_PAYMENT_INTERFACE_035.PAY_URL
     *
     * @mbggenerated
     */
    public String getPayUrl() {
        return payUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.PAY_URL
     *
     * @param payUrl the value for HSPRD.TB_PAYMENT_INTERFACE_035.PAY_URL
     *
     * @mbggenerated
     */
    public void setPayUrl(String payUrl) {
        this.payUrl = payUrl == null ? null : payUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.RETURN_URL
     *
     * @return the value of HSPRD.TB_PAYMENT_INTERFACE_035.RETURN_URL
     *
     * @mbggenerated
     */
    public String getReturnUrl() {
        return returnUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.RETURN_URL
     *
     * @param returnUrl the value for HSPRD.TB_PAYMENT_INTERFACE_035.RETURN_URL
     *
     * @mbggenerated
     */
    public void setReturnUrl(String returnUrl) {
        this.returnUrl = returnUrl == null ? null : returnUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.NOTICE_URL
     *
     * @return the value of HSPRD.TB_PAYMENT_INTERFACE_035.NOTICE_URL
     *
     * @mbggenerated
     */
    public String getNoticeUrl() {
        return noticeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.NOTICE_URL
     *
     * @param noticeUrl the value for HSPRD.TB_PAYMENT_INTERFACE_035.NOTICE_URL
     *
     * @mbggenerated
     */
    public void setNoticeUrl(String noticeUrl) {
        this.noticeUrl = noticeUrl == null ? null : noticeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.IS_ENABLE_SINGLE
     *
     * @return the value of HSPRD.TB_PAYMENT_INTERFACE_035.IS_ENABLE_SINGLE
     *
     * @mbggenerated
     */
    public int getIsEnableSingle() {
        return isEnableSingle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.IS_ENABLE_SINGLE
     *
     * @param isEnableSingle the value for HSPRD.TB_PAYMENT_INTERFACE_035.IS_ENABLE_SINGLE
     *
     * @mbggenerated
     */
    public void setIsEnableSingle(int isEnableSingle) {
        this.isEnableSingle = isEnableSingle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.CHARTSET
     *
     * @return the value of HSPRD.TB_PAYMENT_INTERFACE_035.CHARTSET
     *
     * @mbggenerated
     */
    public String getChartset() {
        return chartset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.CHARTSET
     *
     * @param chartset the value for HSPRD.TB_PAYMENT_INTERFACE_035.CHARTSET
     *
     * @mbggenerated
     */
    public void setChartset(String chartset) {
        this.chartset = chartset == null ? null : chartset.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.INTERFACE_INTO_ACCOUNT
     *
     * @return the value of HSPRD.TB_PAYMENT_INTERFACE_035.INTERFACE_INTO_ACCOUNT
     *
     * @mbggenerated
     */
    public String getInterfaceIntoAccount() {
        return interfaceIntoAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.INTERFACE_INTO_ACCOUNT
     *
     * @param interfaceIntoAccount the value for HSPRD.TB_PAYMENT_INTERFACE_035.INTERFACE_INTO_ACCOUNT
     *
     * @mbggenerated
     */
    public void setInterfaceIntoAccount(String interfaceIntoAccount) {
        this.interfaceIntoAccount = interfaceIntoAccount == null ? null : interfaceIntoAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.NAME
     *
     * @return the value of HSPRD.TB_PAYMENT_INTERFACE_035.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.NAME
     *
     * @param name the value for HSPRD.TB_PAYMENT_INTERFACE_035.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.INTERFACE_VALUE
     *
     * @return the value of HSPRD.TB_PAYMENT_INTERFACE_035.INTERFACE_VALUE
     *
     * @mbggenerated
     */
    public String getInterfaceValue() {
        return interfaceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.INTERFACE_VALUE
     *
     * @param interfaceValue the value for HSPRD.TB_PAYMENT_INTERFACE_035.INTERFACE_VALUE
     *
     * @mbggenerated
     */
    public void setInterfaceValue(String interfaceValue) {
        this.interfaceValue = interfaceValue == null ? null : interfaceValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.IS_ENABLE_UNSINGLE
     *
     * @return the value of HSPRD.TB_PAYMENT_INTERFACE_035.IS_ENABLE_UNSINGLE
     *
     * @mbggenerated
     */
    public int getIsEnableUnsingle() {
        return isEnableUnsingle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.IS_ENABLE_UNSINGLE
     *
     * @param isEnableUnsingle the value for HSPRD.TB_PAYMENT_INTERFACE_035.IS_ENABLE_UNSINGLE
     *
     * @mbggenerated
     */
    public void setIsEnableUnsingle(int isEnableUnsingle) {
        this.isEnableUnsingle = isEnableUnsingle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.SIGN_TYPE
     *
     * @return the value of HSPRD.TB_PAYMENT_INTERFACE_035.SIGN_TYPE
     *
     * @mbggenerated
     */
    public String getSignType() {
        return signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.SIGN_TYPE
     *
     * @param signType the value for HSPRD.TB_PAYMENT_INTERFACE_035.SIGN_TYPE
     *
     * @mbggenerated
     */
    public void setSignType(String signType) {
        this.signType = signType == null ? null : signType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.PAY_STYLE
     *
     * @return the value of HSPRD.TB_PAYMENT_INTERFACE_035.PAY_STYLE
     *
     * @mbggenerated
     */
    public String getPayStyle() {
        return payStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.PAY_STYLE
     *
     * @param payStyle the value for HSPRD.TB_PAYMENT_INTERFACE_035.PAY_STYLE
     *
     * @mbggenerated
     */
    public void setPayStyle(String payStyle) {
        this.payStyle = payStyle == null ? null : payStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.SELLER_EMAIL
     *
     * @return the value of HSPRD.TB_PAYMENT_INTERFACE_035.SELLER_EMAIL
     *
     * @mbggenerated
     */
    public String getSellerEmail() {
        return sellerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.SELLER_EMAIL
     *
     * @param sellerEmail the value for HSPRD.TB_PAYMENT_INTERFACE_035.SELLER_EMAIL
     *
     * @mbggenerated
     */
    public void setSellerEmail(String sellerEmail) {
        this.sellerEmail = sellerEmail == null ? null : sellerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.TRANSPORT
     *
     * @return the value of HSPRD.TB_PAYMENT_INTERFACE_035.TRANSPORT
     *
     * @mbggenerated
     */
    public String getTransport() {
        return transport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.TRANSPORT
     *
     * @param transport the value for HSPRD.TB_PAYMENT_INTERFACE_035.TRANSPORT
     *
     * @mbggenerated
     */
    public void setTransport(String transport) {
        this.transport = transport == null ? null : transport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.ORDER_DESCRIPTION
     *
     * @return the value of HSPRD.TB_PAYMENT_INTERFACE_035.ORDER_DESCRIPTION
     *
     * @mbggenerated
     */
    public String getOrderDescription() {
        return orderDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.ORDER_DESCRIPTION
     *
     * @param orderDescription the value for HSPRD.TB_PAYMENT_INTERFACE_035.ORDER_DESCRIPTION
     *
     * @mbggenerated
     */
    public void setOrderDescription(String orderDescription) {
        this.orderDescription = orderDescription == null ? null : orderDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.ORDER_BY
     *
     * @return the value of HSPRD.TB_PAYMENT_INTERFACE_035.ORDER_BY
     *
     * @mbggenerated
     */
    public long getOrderBy() {
        return orderBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.ORDER_BY
     *
     * @param orderBy the value for HSPRD.TB_PAYMENT_INTERFACE_035.ORDER_BY
     *
     * @mbggenerated
     */
    public void setOrderBy(long orderBy) {
        this.orderBy = orderBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.LOGO_URL
     *
     * @return the value of HSPRD.TB_PAYMENT_INTERFACE_035.LOGO_URL
     *
     * @mbggenerated
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.LOGO_URL
     *
     * @param logoUrl the value for HSPRD.TB_PAYMENT_INTERFACE_035.LOGO_URL
     *
     * @mbggenerated
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl == null ? null : logoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.STATE
     *
     * @return the value of HSPRD.TB_PAYMENT_INTERFACE_035.STATE
     *
     * @mbggenerated
     */
    public int getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_PAYMENT_INTERFACE_035.STATE
     *
     * @param state the value for HSPRD.TB_PAYMENT_INTERFACE_035.STATE
     *
     * @mbggenerated
     */
    public void setState(int state) {
        this.state = state;
    }
}