package com.hszsd.webpay.condition;

import java.util.ArrayList;
import java.util.List;

public class BankInfoCondition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    public BankInfoCondition() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBankIdIsNull() {
            addCriterion("BANK_ID is null");
            return (Criteria) this;
        }

        public Criteria andBankIdIsNotNull() {
            addCriterion("BANK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBankIdEqualTo(Long value) {
            addCriterion("BANK_ID =", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotEqualTo(Long value) {
            addCriterion("BANK_ID <>", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdGreaterThan(Long value) {
            addCriterion("BANK_ID >", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdGreaterThanOrEqualTo(Long value) {
            addCriterion("BANK_ID >=", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLessThan(Long value) {
            addCriterion("BANK_ID <", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLessThanOrEqualTo(Long value) {
            addCriterion("BANK_ID <=", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdIn(List<Long> values) {
            addCriterion("BANK_ID in", values, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotIn(List<Long> values) {
            addCriterion("BANK_ID not in", values, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdBetween(Long value1, Long value2) {
            addCriterion("BANK_ID between", value1, value2, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotBetween(Long value1, Long value2) {
            addCriterion("BANK_ID not between", value1, value2, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNull() {
            addCriterion("BANK_NAME is null");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNotNull() {
            addCriterion("BANK_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andBankNameEqualTo(String value) {
            addCriterion("BANK_NAME =", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotEqualTo(String value) {
            addCriterion("BANK_NAME <>", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThan(String value) {
            addCriterion("BANK_NAME >", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_NAME >=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThan(String value) {
            addCriterion("BANK_NAME <", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThanOrEqualTo(String value) {
            addCriterion("BANK_NAME <=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLike(String value) {
            addCriterion("BANK_NAME like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotLike(String value) {
            addCriterion("BANK_NAME not like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameIn(List<String> values) {
            addCriterion("BANK_NAME in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotIn(List<String> values) {
            addCriterion("BANK_NAME not in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameBetween(String value1, String value2) {
            addCriterion("BANK_NAME between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotBetween(String value1, String value2) {
            addCriterion("BANK_NAME not between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankValueIsNull() {
            addCriterion("BANK_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andBankValueIsNotNull() {
            addCriterion("BANK_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andBankValueEqualTo(String value) {
            addCriterion("BANK_VALUE =", value, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueNotEqualTo(String value) {
            addCriterion("BANK_VALUE <>", value, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueGreaterThan(String value) {
            addCriterion("BANK_VALUE >", value, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_VALUE >=", value, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueLessThan(String value) {
            addCriterion("BANK_VALUE <", value, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueLessThanOrEqualTo(String value) {
            addCriterion("BANK_VALUE <=", value, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueLike(String value) {
            addCriterion("BANK_VALUE like", value, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueNotLike(String value) {
            addCriterion("BANK_VALUE not like", value, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueIn(List<String> values) {
            addCriterion("BANK_VALUE in", values, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueNotIn(List<String> values) {
            addCriterion("BANK_VALUE not in", values, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueBetween(String value1, String value2) {
            addCriterion("BANK_VALUE between", value1, value2, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankValueNotBetween(String value1, String value2) {
            addCriterion("BANK_VALUE not between", value1, value2, "bankValue");
            return (Criteria) this;
        }

        public Criteria andBankLogoPcIsNull() {
            addCriterion("BANK_LOGO_PC is null");
            return (Criteria) this;
        }

        public Criteria andBankLogoPcIsNotNull() {
            addCriterion("BANK_LOGO_PC is not null");
            return (Criteria) this;
        }

        public Criteria andBankLogoPcEqualTo(String value) {
            addCriterion("BANK_LOGO_PC =", value, "bankLogoPc");
            return (Criteria) this;
        }

        public Criteria andBankLogoPcNotEqualTo(String value) {
            addCriterion("BANK_LOGO_PC <>", value, "bankLogoPc");
            return (Criteria) this;
        }

        public Criteria andBankLogoPcGreaterThan(String value) {
            addCriterion("BANK_LOGO_PC >", value, "bankLogoPc");
            return (Criteria) this;
        }

        public Criteria andBankLogoPcGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_LOGO_PC >=", value, "bankLogoPc");
            return (Criteria) this;
        }

        public Criteria andBankLogoPcLessThan(String value) {
            addCriterion("BANK_LOGO_PC <", value, "bankLogoPc");
            return (Criteria) this;
        }

        public Criteria andBankLogoPcLessThanOrEqualTo(String value) {
            addCriterion("BANK_LOGO_PC <=", value, "bankLogoPc");
            return (Criteria) this;
        }

        public Criteria andBankLogoPcLike(String value) {
            addCriterion("BANK_LOGO_PC like", value, "bankLogoPc");
            return (Criteria) this;
        }

        public Criteria andBankLogoPcNotLike(String value) {
            addCriterion("BANK_LOGO_PC not like", value, "bankLogoPc");
            return (Criteria) this;
        }

        public Criteria andBankLogoPcIn(List<String> values) {
            addCriterion("BANK_LOGO_PC in", values, "bankLogoPc");
            return (Criteria) this;
        }

        public Criteria andBankLogoPcNotIn(List<String> values) {
            addCriterion("BANK_LOGO_PC not in", values, "bankLogoPc");
            return (Criteria) this;
        }

        public Criteria andBankLogoPcBetween(String value1, String value2) {
            addCriterion("BANK_LOGO_PC between", value1, value2, "bankLogoPc");
            return (Criteria) this;
        }

        public Criteria andBankLogoPcNotBetween(String value1, String value2) {
            addCriterion("BANK_LOGO_PC not between", value1, value2, "bankLogoPc");
            return (Criteria) this;
        }

        public Criteria andBankLogoMobIsNull() {
            addCriterion("BANK_LOGO_MOB is null");
            return (Criteria) this;
        }

        public Criteria andBankLogoMobIsNotNull() {
            addCriterion("BANK_LOGO_MOB is not null");
            return (Criteria) this;
        }

        public Criteria andBankLogoMobEqualTo(String value) {
            addCriterion("BANK_LOGO_MOB =", value, "bankLogoMob");
            return (Criteria) this;
        }

        public Criteria andBankLogoMobNotEqualTo(String value) {
            addCriterion("BANK_LOGO_MOB <>", value, "bankLogoMob");
            return (Criteria) this;
        }

        public Criteria andBankLogoMobGreaterThan(String value) {
            addCriterion("BANK_LOGO_MOB >", value, "bankLogoMob");
            return (Criteria) this;
        }

        public Criteria andBankLogoMobGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_LOGO_MOB >=", value, "bankLogoMob");
            return (Criteria) this;
        }

        public Criteria andBankLogoMobLessThan(String value) {
            addCriterion("BANK_LOGO_MOB <", value, "bankLogoMob");
            return (Criteria) this;
        }

        public Criteria andBankLogoMobLessThanOrEqualTo(String value) {
            addCriterion("BANK_LOGO_MOB <=", value, "bankLogoMob");
            return (Criteria) this;
        }

        public Criteria andBankLogoMobLike(String value) {
            addCriterion("BANK_LOGO_MOB like", value, "bankLogoMob");
            return (Criteria) this;
        }

        public Criteria andBankLogoMobNotLike(String value) {
            addCriterion("BANK_LOGO_MOB not like", value, "bankLogoMob");
            return (Criteria) this;
        }

        public Criteria andBankLogoMobIn(List<String> values) {
            addCriterion("BANK_LOGO_MOB in", values, "bankLogoMob");
            return (Criteria) this;
        }

        public Criteria andBankLogoMobNotIn(List<String> values) {
            addCriterion("BANK_LOGO_MOB not in", values, "bankLogoMob");
            return (Criteria) this;
        }

        public Criteria andBankLogoMobBetween(String value1, String value2) {
            addCriterion("BANK_LOGO_MOB between", value1, value2, "bankLogoMob");
            return (Criteria) this;
        }

        public Criteria andBankLogoMobNotBetween(String value1, String value2) {
            addCriterion("BANK_LOGO_MOB not between", value1, value2, "bankLogoMob");
            return (Criteria) this;
        }

        public Criteria andQuickFlagIsNull() {
            addCriterion("QUICK_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andQuickFlagIsNotNull() {
            addCriterion("QUICK_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andQuickFlagEqualTo(int value) {
            addCriterion("QUICK_FLAG =", value, "quickFlag");
            return (Criteria) this;
        }

        public Criteria andQuickFlagNotEqualTo(int value) {
            addCriterion("QUICK_FLAG <>", value, "quickFlag");
            return (Criteria) this;
        }

        public Criteria andQuickFlagGreaterThan(int value) {
            addCriterion("QUICK_FLAG >", value, "quickFlag");
            return (Criteria) this;
        }

        public Criteria andQuickFlagGreaterThanOrEqualTo(int value) {
            addCriterion("QUICK_FLAG >=", value, "quickFlag");
            return (Criteria) this;
        }

        public Criteria andQuickFlagLessThan(int value) {
            addCriterion("QUICK_FLAG <", value, "quickFlag");
            return (Criteria) this;
        }

        public Criteria andQuickFlagLessThanOrEqualTo(int value) {
            addCriterion("QUICK_FLAG <=", value, "quickFlag");
            return (Criteria) this;
        }

        public Criteria andQuickFlagIn(List<Integer> values) {
            addCriterion("QUICK_FLAG in", values, "quickFlag");
            return (Criteria) this;
        }

        public Criteria andQuickFlagNotIn(List<Integer> values) {
            addCriterion("QUICK_FLAG not in", values, "quickFlag");
            return (Criteria) this;
        }

        public Criteria andQuickFlagBetween(int value1, int value2) {
            addCriterion("QUICK_FLAG between", value1, value2, "quickFlag");
            return (Criteria) this;
        }

        public Criteria andQuickFlagNotBetween(int value1, int value2) {
            addCriterion("QUICK_FLAG not between", value1, value2, "quickFlag");
            return (Criteria) this;
        }

        public Criteria andIsEnablePcIsNull() {
            addCriterion("IS_ENABLE_PC is null");
            return (Criteria) this;
        }

        public Criteria andIsEnablePcIsNotNull() {
            addCriterion("IS_ENABLE_PC is not null");
            return (Criteria) this;
        }

        public Criteria andIsEnablePcEqualTo(int value) {
            addCriterion("IS_ENABLE_PC =", value, "isEnablePc");
            return (Criteria) this;
        }

        public Criteria andIsEnablePcNotEqualTo(int value) {
            addCriterion("IS_ENABLE_PC <>", value, "isEnablePc");
            return (Criteria) this;
        }

        public Criteria andIsEnablePcGreaterThan(int value) {
            addCriterion("IS_ENABLE_PC >", value, "isEnablePc");
            return (Criteria) this;
        }

        public Criteria andIsEnablePcGreaterThanOrEqualTo(int value) {
            addCriterion("IS_ENABLE_PC >=", value, "isEnablePc");
            return (Criteria) this;
        }

        public Criteria andIsEnablePcLessThan(int value) {
            addCriterion("IS_ENABLE_PC <", value, "isEnablePc");
            return (Criteria) this;
        }

        public Criteria andIsEnablePcLessThanOrEqualTo(int value) {
            addCriterion("IS_ENABLE_PC <=", value, "isEnablePc");
            return (Criteria) this;
        }

        public Criteria andIsEnablePcIn(List<Integer> values) {
            addCriterion("IS_ENABLE_PC in", values, "isEnablePc");
            return (Criteria) this;
        }

        public Criteria andIsEnablePcNotIn(List<Integer> values) {
            addCriterion("IS_ENABLE_PC not in", values, "isEnablePc");
            return (Criteria) this;
        }

        public Criteria andIsEnablePcBetween(int value1, int value2) {
            addCriterion("IS_ENABLE_PC between", value1, value2, "isEnablePc");
            return (Criteria) this;
        }

        public Criteria andIsEnablePcNotBetween(int value1, int value2) {
            addCriterion("IS_ENABLE_PC not between", value1, value2, "isEnablePc");
            return (Criteria) this;
        }

        public Criteria andIsEnableMobIsNull() {
            addCriterion("IS_ENABLE_MOB is null");
            return (Criteria) this;
        }

        public Criteria andIsEnableMobIsNotNull() {
            addCriterion("IS_ENABLE_MOB is not null");
            return (Criteria) this;
        }

        public Criteria andIsEnableMobEqualTo(int value) {
            addCriterion("IS_ENABLE_MOB =", value, "isEnableMob");
            return (Criteria) this;
        }

        public Criteria andIsEnableMobNotEqualTo(int value) {
            addCriterion("IS_ENABLE_MOB <>", value, "isEnableMob");
            return (Criteria) this;
        }

        public Criteria andIsEnableMobGreaterThan(int value) {
            addCriterion("IS_ENABLE_MOB >", value, "isEnableMob");
            return (Criteria) this;
        }

        public Criteria andIsEnableMobGreaterThanOrEqualTo(int value) {
            addCriterion("IS_ENABLE_MOB >=", value, "isEnableMob");
            return (Criteria) this;
        }

        public Criteria andIsEnableMobLessThan(int value) {
            addCriterion("IS_ENABLE_MOB <", value, "isEnableMob");
            return (Criteria) this;
        }

        public Criteria andIsEnableMobLessThanOrEqualTo(int value) {
            addCriterion("IS_ENABLE_MOB <=", value, "isEnableMob");
            return (Criteria) this;
        }

        public Criteria andIsEnableMobIn(List<Integer> values) {
            addCriterion("IS_ENABLE_MOB in", values, "isEnableMob");
            return (Criteria) this;
        }

        public Criteria andIsEnableMobNotIn(List<Integer> values) {
            addCriterion("IS_ENABLE_MOB not in", values, "isEnableMob");
            return (Criteria) this;
        }

        public Criteria andIsEnableMobBetween(int value1, int value2) {
            addCriterion("IS_ENABLE_MOB between", value1, value2, "isEnableMob");
            return (Criteria) this;
        }

        public Criteria andIsEnableMobNotBetween(int value1, int value2) {
            addCriterion("IS_ENABLE_MOB not between", value1, value2, "isEnableMob");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HSPAY.TB_BANK_INFO
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}