package com.hszsd.webpay.po;

public class OnlineBankPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_ONLINE_BANK_034.ID
     *
     * @mbggenerated
     */
    private long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_ONLINE_BANK_034.BANK_NAME
     *
     * @mbggenerated
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_ONLINE_BANK_034.BANK_LOGO
     *
     * @mbggenerated
     */
    private String bankLogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_ONLINE_BANK_034.BANK_VALUE
     *
     * @mbggenerated
     */
    private String bankValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_ONLINE_BANK_034.PAYMENT_INTERFACE_ID
     *
     * @mbggenerated
     */
    private String paymentInterfaceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_ONLINE_BANK_034.IS_ENABLE
     *
     * @mbggenerated
     */
    private int isEnable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_ONLINE_BANK_034.ID
     *
     * @return the value of HSPRD.TB_ONLINE_BANK_034.ID
     *
     * @mbggenerated
     */
    public long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_ONLINE_BANK_034.ID
     *
     * @param id the value for HSPRD.TB_ONLINE_BANK_034.ID
     *
     * @mbggenerated
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_ONLINE_BANK_034.BANK_NAME
     *
     * @return the value of HSPRD.TB_ONLINE_BANK_034.BANK_NAME
     *
     * @mbggenerated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_ONLINE_BANK_034.BANK_NAME
     *
     * @param bankName the value for HSPRD.TB_ONLINE_BANK_034.BANK_NAME
     *
     * @mbggenerated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_ONLINE_BANK_034.BANK_LOGO
     *
     * @return the value of HSPRD.TB_ONLINE_BANK_034.BANK_LOGO
     *
     * @mbggenerated
     */
    public String getBankLogo() {
        return bankLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_ONLINE_BANK_034.BANK_LOGO
     *
     * @param bankLogo the value for HSPRD.TB_ONLINE_BANK_034.BANK_LOGO
     *
     * @mbggenerated
     */
    public void setBankLogo(String bankLogo) {
        this.bankLogo = bankLogo == null ? null : bankLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_ONLINE_BANK_034.BANK_VALUE
     *
     * @return the value of HSPRD.TB_ONLINE_BANK_034.BANK_VALUE
     *
     * @mbggenerated
     */
    public String getBankValue() {
        return bankValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_ONLINE_BANK_034.BANK_VALUE
     *
     * @param bankValue the value for HSPRD.TB_ONLINE_BANK_034.BANK_VALUE
     *
     * @mbggenerated
     */
    public void setBankValue(String bankValue) {
        this.bankValue = bankValue == null ? null : bankValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_ONLINE_BANK_034.PAYMENT_INTERFACE_ID
     *
     * @return the value of HSPRD.TB_ONLINE_BANK_034.PAYMENT_INTERFACE_ID
     *
     * @mbggenerated
     */
    public String getPaymentInterfaceId() {
        return paymentInterfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_ONLINE_BANK_034.PAYMENT_INTERFACE_ID
     *
     * @param paymentInterfaceId the value for HSPRD.TB_ONLINE_BANK_034.PAYMENT_INTERFACE_ID
     *
     * @mbggenerated
     */
    public void setPaymentInterfaceId(String paymentInterfaceId) {
        this.paymentInterfaceId = paymentInterfaceId == null ? null : paymentInterfaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_ONLINE_BANK_034.IS_ENABLE
     *
     * @return the value of HSPRD.TB_ONLINE_BANK_034.IS_ENABLE
     *
     * @mbggenerated
     */
    public int getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_ONLINE_BANK_034.IS_ENABLE
     *
     * @param isEnable the value for HSPRD.TB_ONLINE_BANK_034.IS_ENABLE
     *
     * @mbggenerated
     */
    public void setIsEnable(int isEnable) {
        this.isEnable = isEnable;
    }
}