package com.hszsd.webpay.po;

import java.math.BigDecimal;

public class RechargeRecordPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_RECHARGE_RECORD_028.ID
     *
     * @mbggenerated
     */
    private long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_RECHARGE_RECORD_028.TRADE_NO
     *
     * @mbggenerated
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_RECHARGE_RECORD_028.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_RECHARGE_RECORD_028.STATUS
     *
     * @mbggenerated
     */
    private int status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_RECHARGE_RECORD_028.MONEY
     *
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_RECHARGE_RECORD_028.PAYMENT
     *
     * @mbggenerated
     */
    private String payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_RECHARGE_RECORD_028.RETVALUE
     *
     * @mbggenerated
     */
    private String retvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_RECHARGE_RECORD_028.TYPE
     *
     * @mbggenerated
     */
    private int type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_RECHARGE_RECORD_028.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_RECHARGE_RECORD_028.ADDTIME
     *
     * @mbggenerated
     */
    private long addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_RECHARGE_RECORD_028.AUDIT_TIME
     *
     * @mbggenerated
     */
    private long auditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPRD.TB_RECHARGE_RECORD_028.AUDIT_USERID
     *
     * @mbggenerated
     */
    private long auditUserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_RECHARGE_RECORD_028.ID
     *
     * @return the value of HSPRD.TB_RECHARGE_RECORD_028.ID
     *
     * @mbggenerated
     */
    public long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_RECHARGE_RECORD_028.ID
     *
     * @param id the value for HSPRD.TB_RECHARGE_RECORD_028.ID
     *
     * @mbggenerated
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_RECHARGE_RECORD_028.TRADE_NO
     *
     * @return the value of HSPRD.TB_RECHARGE_RECORD_028.TRADE_NO
     *
     * @mbggenerated
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_RECHARGE_RECORD_028.TRADE_NO
     *
     * @param tradeNo the value for HSPRD.TB_RECHARGE_RECORD_028.TRADE_NO
     *
     * @mbggenerated
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_RECHARGE_RECORD_028.USER_ID
     *
     * @return the value of HSPRD.TB_RECHARGE_RECORD_028.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_RECHARGE_RECORD_028.USER_ID
     *
     * @param userId the value for HSPRD.TB_RECHARGE_RECORD_028.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_RECHARGE_RECORD_028.STATUS
     *
     * @return the value of HSPRD.TB_RECHARGE_RECORD_028.STATUS
     *
     * @mbggenerated
     */
    public int getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_RECHARGE_RECORD_028.STATUS
     *
     * @param status the value for HSPRD.TB_RECHARGE_RECORD_028.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(int status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_RECHARGE_RECORD_028.MONEY
     *
     * @return the value of HSPRD.TB_RECHARGE_RECORD_028.MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_RECHARGE_RECORD_028.MONEY
     *
     * @param money the value for HSPRD.TB_RECHARGE_RECORD_028.MONEY
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_RECHARGE_RECORD_028.PAYMENT
     *
     * @return the value of HSPRD.TB_RECHARGE_RECORD_028.PAYMENT
     *
     * @mbggenerated
     */
    public String getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_RECHARGE_RECORD_028.PAYMENT
     *
     * @param payment the value for HSPRD.TB_RECHARGE_RECORD_028.PAYMENT
     *
     * @mbggenerated
     */
    public void setPayment(String payment) {
        this.payment = payment == null ? null : payment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_RECHARGE_RECORD_028.RETVALUE
     *
     * @return the value of HSPRD.TB_RECHARGE_RECORD_028.RETVALUE
     *
     * @mbggenerated
     */
    public String getRetvalue() {
        return retvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_RECHARGE_RECORD_028.RETVALUE
     *
     * @param retvalue the value for HSPRD.TB_RECHARGE_RECORD_028.RETVALUE
     *
     * @mbggenerated
     */
    public void setRetvalue(String retvalue) {
        this.retvalue = retvalue == null ? null : retvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_RECHARGE_RECORD_028.TYPE
     *
     * @return the value of HSPRD.TB_RECHARGE_RECORD_028.TYPE
     *
     * @mbggenerated
     */
    public int getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_RECHARGE_RECORD_028.TYPE
     *
     * @param type the value for HSPRD.TB_RECHARGE_RECORD_028.TYPE
     *
     * @mbggenerated
     */
    public void setType(int type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_RECHARGE_RECORD_028.REMARK
     *
     * @return the value of HSPRD.TB_RECHARGE_RECORD_028.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_RECHARGE_RECORD_028.REMARK
     *
     * @param remark the value for HSPRD.TB_RECHARGE_RECORD_028.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_RECHARGE_RECORD_028.ADDTIME
     *
     * @return the value of HSPRD.TB_RECHARGE_RECORD_028.ADDTIME
     *
     * @mbggenerated
     */
    public long getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_RECHARGE_RECORD_028.ADDTIME
     *
     * @param addtime the value for HSPRD.TB_RECHARGE_RECORD_028.ADDTIME
     *
     * @mbggenerated
     */
    public void setAddtime(long addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_RECHARGE_RECORD_028.AUDIT_TIME
     *
     * @return the value of HSPRD.TB_RECHARGE_RECORD_028.AUDIT_TIME
     *
     * @mbggenerated
     */
    public long getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_RECHARGE_RECORD_028.AUDIT_TIME
     *
     * @param auditTime the value for HSPRD.TB_RECHARGE_RECORD_028.AUDIT_TIME
     *
     * @mbggenerated
     */
    public void setAuditTime(long auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPRD.TB_RECHARGE_RECORD_028.AUDIT_USERID
     *
     * @return the value of HSPRD.TB_RECHARGE_RECORD_028.AUDIT_USERID
     *
     * @mbggenerated
     */
    public long getAuditUserid() {
        return auditUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPRD.TB_RECHARGE_RECORD_028.AUDIT_USERID
     *
     * @param auditUserid the value for HSPRD.TB_RECHARGE_RECORD_028.AUDIT_USERID
     *
     * @mbggenerated
     */
    public void setAuditUserid(long auditUserid) {
        this.auditUserid = auditUserid;
    }
}