package com.hszsd.webpay.po;

import java.util.Date;

public class TradeCallbackPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_CALLBACK.TRANS_ID
     *
     * @mbggenerated
     */
    private String transId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_CALLBACK.COUNT
     *
     * @mbggenerated
     */
    private int count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_CALLBACK.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_CALLBACK.CREATE_BY
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_CALLBACK.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_CALLBACK.UPDATE_BY
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_CALLBACK.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_CALLBACK.TRANS_ID
     *
     * @return the value of HSPAY.TB_TRADE_CALLBACK.TRANS_ID
     *
     * @mbggenerated
     */
    public String getTransId() {
        return transId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_CALLBACK.TRANS_ID
     *
     * @param transId the value for HSPAY.TB_TRADE_CALLBACK.TRANS_ID
     *
     * @mbggenerated
     */
    public void setTransId(String transId) {
        this.transId = transId == null ? null : transId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_CALLBACK.COUNT
     *
     * @return the value of HSPAY.TB_TRADE_CALLBACK.COUNT
     *
     * @mbggenerated
     */
    public int getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_CALLBACK.COUNT
     *
     * @param count the value for HSPAY.TB_TRADE_CALLBACK.COUNT
     *
     * @mbggenerated
     */
    public void setCount(int count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_CALLBACK.CREATE_DATE
     *
     * @return the value of HSPAY.TB_TRADE_CALLBACK.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_CALLBACK.CREATE_DATE
     *
     * @param createDate the value for HSPAY.TB_TRADE_CALLBACK.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_CALLBACK.CREATE_BY
     *
     * @return the value of HSPAY.TB_TRADE_CALLBACK.CREATE_BY
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_CALLBACK.CREATE_BY
     *
     * @param createBy the value for HSPAY.TB_TRADE_CALLBACK.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_CALLBACK.UPDATE_DATE
     *
     * @return the value of HSPAY.TB_TRADE_CALLBACK.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_CALLBACK.UPDATE_DATE
     *
     * @param updateDate the value for HSPAY.TB_TRADE_CALLBACK.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_CALLBACK.UPDATE_BY
     *
     * @return the value of HSPAY.TB_TRADE_CALLBACK.UPDATE_BY
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_CALLBACK.UPDATE_BY
     *
     * @param updateBy the value for HSPAY.TB_TRADE_CALLBACK.UPDATE_BY
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_CALLBACK.REMARK
     *
     * @return the value of HSPAY.TB_TRADE_CALLBACK.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_CALLBACK.REMARK
     *
     * @param remark the value for HSPAY.TB_TRADE_CALLBACK.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}