package com.hszsd.webpay.dao;

import com.hszsd.webpay.po.TradeCallbackPO;
import com.hszsd.webpay.condition.TradeCallbackCondition;
import java.util.List;

import com.hszsd.webpay.web.dto.TradeCallbackDTO;
import org.apache.ibatis.annotations.Param;

public interface TradeCallbackDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_CALLBACK
     *
     * @mbggenerated
     */
    int countByCondition(TradeCallbackCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_CALLBACK
     *
     * @mbggenerated
     */
    int deleteByCondition(TradeCallbackCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_CALLBACK
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String transId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_CALLBACK
     *
     * @mbggenerated
     */
    int insert(TradeCallbackPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_CALLBACK
     *
     * @mbggenerated
     */
    int insertSelective(TradeCallbackPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_CALLBACK
     *
     * @mbggenerated
     */
    List<TradeCallbackDTO> selectByCondition(TradeCallbackCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_CALLBACK
     *
     * @mbggenerated
     */
    TradeCallbackDTO selectByPrimaryKey(String transId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_CALLBACK
     *
     * @mbggenerated
     */
    int updateByConditionSelective(@Param("record") TradeCallbackPO record, @Param("condition") TradeCallbackCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_CALLBACK
     *
     * @mbggenerated
     */
    int updateByCondition(@Param("record") TradeCallbackPO record, @Param("condition") TradeCallbackCondition condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_CALLBACK
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradeCallbackPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HSPAY.TB_TRADE_CALLBACK
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradeCallbackPO record);
}