package com.hszsd.webpay.po;

import java.util.Date;

public class AccountQuickBankPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_QUICK_BANK.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_QUICK_BANK.USER_TYPE
     *
     * @mbggenerated
     */
    private int userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_QUICK_BANK.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_QUICK_BANK.REQUEST_ID
     *
     * @mbggenerated
     */
    private String requestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_QUICK_BANK.USER_IP
     *
     * @mbggenerated
     */
    private String userIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_QUICK_BANK.CARD_TOP
     *
     * @mbggenerated
     */
    private String cardTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_QUICK_BANK.CARD_LAST
     *
     * @mbggenerated
     */
    private String cardLast;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_QUICK_BANK.BANK_CODE
     *
     * @mbggenerated
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_QUICK_BANK.BIND_STATUS
     *
     * @mbggenerated
     */
    private int bindStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_QUICK_BANK.VALID_STATUS
     *
     * @mbggenerated
     */
    private int validStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_QUICK_BANK.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_QUICK_BANK.CREATE_BY
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_QUICK_BANK.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_QUICK_BANK.UPDATE_BY
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.ID
     *
     * @return the value of HSPAY.TB_ACCOUNT_QUICK_BANK.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.ID
     *
     * @param id the value for HSPAY.TB_ACCOUNT_QUICK_BANK.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.USER_TYPE
     *
     * @return the value of HSPAY.TB_ACCOUNT_QUICK_BANK.USER_TYPE
     *
     * @mbggenerated
     */
    public int getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.USER_TYPE
     *
     * @param userType the value for HSPAY.TB_ACCOUNT_QUICK_BANK.USER_TYPE
     *
     * @mbggenerated
     */
    public void setUserType(int userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.USER_ID
     *
     * @return the value of HSPAY.TB_ACCOUNT_QUICK_BANK.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.USER_ID
     *
     * @param userId the value for HSPAY.TB_ACCOUNT_QUICK_BANK.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.REQUEST_ID
     *
     * @return the value of HSPAY.TB_ACCOUNT_QUICK_BANK.REQUEST_ID
     *
     * @mbggenerated
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.REQUEST_ID
     *
     * @param requestId the value for HSPAY.TB_ACCOUNT_QUICK_BANK.REQUEST_ID
     *
     * @mbggenerated
     */
    public void setRequestId(String requestId) {
        this.requestId = requestId == null ? null : requestId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.USER_IP
     *
     * @return the value of HSPAY.TB_ACCOUNT_QUICK_BANK.USER_IP
     *
     * @mbggenerated
     */
    public String getUserIp() {
        return userIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.USER_IP
     *
     * @param userIp the value for HSPAY.TB_ACCOUNT_QUICK_BANK.USER_IP
     *
     * @mbggenerated
     */
    public void setUserIp(String userIp) {
        this.userIp = userIp == null ? null : userIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.CARD_TOP
     *
     * @return the value of HSPAY.TB_ACCOUNT_QUICK_BANK.CARD_TOP
     *
     * @mbggenerated
     */
    public String getCardTop() {
        return cardTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.CARD_TOP
     *
     * @param cardTop the value for HSPAY.TB_ACCOUNT_QUICK_BANK.CARD_TOP
     *
     * @mbggenerated
     */
    public void setCardTop(String cardTop) {
        this.cardTop = cardTop == null ? null : cardTop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.CARD_LAST
     *
     * @return the value of HSPAY.TB_ACCOUNT_QUICK_BANK.CARD_LAST
     *
     * @mbggenerated
     */
    public String getCardLast() {
        return cardLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.CARD_LAST
     *
     * @param cardLast the value for HSPAY.TB_ACCOUNT_QUICK_BANK.CARD_LAST
     *
     * @mbggenerated
     */
    public void setCardLast(String cardLast) {
        this.cardLast = cardLast == null ? null : cardLast.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.BANK_CODE
     *
     * @return the value of HSPAY.TB_ACCOUNT_QUICK_BANK.BANK_CODE
     *
     * @mbggenerated
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.BANK_CODE
     *
     * @param bankCode the value for HSPAY.TB_ACCOUNT_QUICK_BANK.BANK_CODE
     *
     * @mbggenerated
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.BIND_STATUS
     *
     * @return the value of HSPAY.TB_ACCOUNT_QUICK_BANK.BIND_STATUS
     *
     * @mbggenerated
     */
    public int getBindStatus() {
        return bindStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.BIND_STATUS
     *
     * @param bindStatus the value for HSPAY.TB_ACCOUNT_QUICK_BANK.BIND_STATUS
     *
     * @mbggenerated
     */
    public void setBindStatus(int bindStatus) {
        this.bindStatus = bindStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.VALID_STATUS
     *
     * @return the value of HSPAY.TB_ACCOUNT_QUICK_BANK.VALID_STATUS
     *
     * @mbggenerated
     */
    public int getValidStatus() {
        return validStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.VALID_STATUS
     *
     * @param validStatus the value for HSPAY.TB_ACCOUNT_QUICK_BANK.VALID_STATUS
     *
     * @mbggenerated
     */
    public void setValidStatus(int validStatus) {
        this.validStatus = validStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.CREATE_DATE
     *
     * @return the value of HSPAY.TB_ACCOUNT_QUICK_BANK.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.CREATE_DATE
     *
     * @param createDate the value for HSPAY.TB_ACCOUNT_QUICK_BANK.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.CREATE_BY
     *
     * @return the value of HSPAY.TB_ACCOUNT_QUICK_BANK.CREATE_BY
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.CREATE_BY
     *
     * @param createBy the value for HSPAY.TB_ACCOUNT_QUICK_BANK.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.UPDATE_DATE
     *
     * @return the value of HSPAY.TB_ACCOUNT_QUICK_BANK.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.UPDATE_DATE
     *
     * @param updateDate the value for HSPAY.TB_ACCOUNT_QUICK_BANK.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.UPDATE_BY
     *
     * @return the value of HSPAY.TB_ACCOUNT_QUICK_BANK.UPDATE_BY
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_QUICK_BANK.UPDATE_BY
     *
     * @param updateBy the value for HSPAY.TB_ACCOUNT_QUICK_BANK.UPDATE_BY
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }
}