package com.hszsd.webpay.po;

import java.util.Date;

public class AccountBankPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_BANK.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_BANK.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_BANK.ACCOUNT
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_BANK.BANK
     *
     * @mbggenerated
     */
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_BANK.REQUEST_ID
     *
     * @mbggenerated
     */
    private String requestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_BANK.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_BANK.CREATE_BY
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_BANK.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_BANK.UPDATE_BY
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_ACCOUNT_BANK.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_BANK.ID
     *
     * @return the value of HSPAY.TB_ACCOUNT_BANK.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_BANK.ID
     *
     * @param id the value for HSPAY.TB_ACCOUNT_BANK.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_BANK.USER_ID
     *
     * @return the value of HSPAY.TB_ACCOUNT_BANK.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_BANK.USER_ID
     *
     * @param userId the value for HSPAY.TB_ACCOUNT_BANK.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_BANK.ACCOUNT
     *
     * @return the value of HSPAY.TB_ACCOUNT_BANK.ACCOUNT
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_BANK.ACCOUNT
     *
     * @param account the value for HSPAY.TB_ACCOUNT_BANK.ACCOUNT
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_BANK.BANK
     *
     * @return the value of HSPAY.TB_ACCOUNT_BANK.BANK
     *
     * @mbggenerated
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_BANK.BANK
     *
     * @param bank the value for HSPAY.TB_ACCOUNT_BANK.BANK
     *
     * @mbggenerated
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_BANK.REQUEST_ID
     *
     * @return the value of HSPAY.TB_ACCOUNT_BANK.REQUEST_ID
     *
     * @mbggenerated
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_BANK.REQUEST_ID
     *
     * @param requestId the value for HSPAY.TB_ACCOUNT_BANK.REQUEST_ID
     *
     * @mbggenerated
     */
    public void setRequestId(String requestId) {
        this.requestId = requestId == null ? null : requestId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_BANK.CREATE_DATE
     *
     * @return the value of HSPAY.TB_ACCOUNT_BANK.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_BANK.CREATE_DATE
     *
     * @param createDate the value for HSPAY.TB_ACCOUNT_BANK.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_BANK.CREATE_BY
     *
     * @return the value of HSPAY.TB_ACCOUNT_BANK.CREATE_BY
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_BANK.CREATE_BY
     *
     * @param createBy the value for HSPAY.TB_ACCOUNT_BANK.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_BANK.UPDATE_DATE
     *
     * @return the value of HSPAY.TB_ACCOUNT_BANK.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_BANK.UPDATE_DATE
     *
     * @param updateDate the value for HSPAY.TB_ACCOUNT_BANK.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_BANK.UPDATE_BY
     *
     * @return the value of HSPAY.TB_ACCOUNT_BANK.UPDATE_BY
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_BANK.UPDATE_BY
     *
     * @param updateBy the value for HSPAY.TB_ACCOUNT_BANK.UPDATE_BY
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_ACCOUNT_BANK.REMARK
     *
     * @return the value of HSPAY.TB_ACCOUNT_BANK.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_ACCOUNT_BANK.REMARK
     *
     * @param remark the value for HSPAY.TB_ACCOUNT_BANK.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}