package com.hszsd.webpay.po;

public class BankInfoPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_BANK_INFO.BANK_ID
     *
     * @mbggenerated
     */
    private long bankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_BANK_INFO.BANK_NAME
     *
     * @mbggenerated
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_BANK_INFO.BANK_VALUE
     *
     * @mbggenerated
     */
    private String bankValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_BANK_INFO.BANK_LOGO_PC
     *
     * @mbggenerated
     */
    private String bankLogoPc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_BANK_INFO.BANK_LOGO_MOB
     *
     * @mbggenerated
     */
    private String bankLogoMob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_BANK_INFO.QUICK_FLAG
     *
     * @mbggenerated
     */
    private int quickFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_BANK_INFO.IS_ENABLE_PC
     *
     * @mbggenerated
     */
    private int isEnablePc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_BANK_INFO.IS_ENABLE_MOB
     *
     * @mbggenerated
     */
    private int isEnableMob;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_BANK_INFO.BANK_ID
     *
     * @return the value of HSPAY.TB_BANK_INFO.BANK_ID
     *
     * @mbggenerated
     */
    public long getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_BANK_INFO.BANK_ID
     *
     * @param bankId the value for HSPAY.TB_BANK_INFO.BANK_ID
     *
     * @mbggenerated
     */
    public void setBankId(long bankId) {
        this.bankId = bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_BANK_INFO.BANK_NAME
     *
     * @return the value of HSPAY.TB_BANK_INFO.BANK_NAME
     *
     * @mbggenerated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_BANK_INFO.BANK_NAME
     *
     * @param bankName the value for HSPAY.TB_BANK_INFO.BANK_NAME
     *
     * @mbggenerated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_BANK_INFO.BANK_VALUE
     *
     * @return the value of HSPAY.TB_BANK_INFO.BANK_VALUE
     *
     * @mbggenerated
     */
    public String getBankValue() {
        return bankValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_BANK_INFO.BANK_VALUE
     *
     * @param bankValue the value for HSPAY.TB_BANK_INFO.BANK_VALUE
     *
     * @mbggenerated
     */
    public void setBankValue(String bankValue) {
        this.bankValue = bankValue == null ? null : bankValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_BANK_INFO.BANK_LOGO_PC
     *
     * @return the value of HSPAY.TB_BANK_INFO.BANK_LOGO_PC
     *
     * @mbggenerated
     */
    public String getBankLogoPc() {
        return bankLogoPc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_BANK_INFO.BANK_LOGO_PC
     *
     * @param bankLogoPc the value for HSPAY.TB_BANK_INFO.BANK_LOGO_PC
     *
     * @mbggenerated
     */
    public void setBankLogoPc(String bankLogoPc) {
        this.bankLogoPc = bankLogoPc == null ? null : bankLogoPc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_BANK_INFO.BANK_LOGO_MOB
     *
     * @return the value of HSPAY.TB_BANK_INFO.BANK_LOGO_MOB
     *
     * @mbggenerated
     */
    public String getBankLogoMob() {
        return bankLogoMob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_BANK_INFO.BANK_LOGO_MOB
     *
     * @param bankLogoMob the value for HSPAY.TB_BANK_INFO.BANK_LOGO_MOB
     *
     * @mbggenerated
     */
    public void setBankLogoMob(String bankLogoMob) {
        this.bankLogoMob = bankLogoMob == null ? null : bankLogoMob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_BANK_INFO.QUICK_FLAG
     *
     * @return the value of HSPAY.TB_BANK_INFO.QUICK_FLAG
     *
     * @mbggenerated
     */
    public int getQuickFlag() {
        return quickFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_BANK_INFO.QUICK_FLAG
     *
     * @param quickFlag the value for HSPAY.TB_BANK_INFO.QUICK_FLAG
     *
     * @mbggenerated
     */
    public void setQuickFlag(int quickFlag) {
        this.quickFlag = quickFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_BANK_INFO.IS_ENABLE_PC
     *
     * @return the value of HSPAY.TB_BANK_INFO.IS_ENABLE_PC
     *
     * @mbggenerated
     */
    public int getIsEnablePc() {
        return isEnablePc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_BANK_INFO.IS_ENABLE_PC
     *
     * @param isEnablePc the value for HSPAY.TB_BANK_INFO.IS_ENABLE_PC
     *
     * @mbggenerated
     */
    public void setIsEnablePc(int isEnablePc) {
        this.isEnablePc = isEnablePc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_BANK_INFO.IS_ENABLE_MOB
     *
     * @return the value of HSPAY.TB_BANK_INFO.IS_ENABLE_MOB
     *
     * @mbggenerated
     */
    public int getIsEnableMob() {
        return isEnableMob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_BANK_INFO.IS_ENABLE_MOB
     *
     * @param isEnableMob the value for HSPAY.TB_BANK_INFO.IS_ENABLE_MOB
     *
     * @mbggenerated
     */
    public void setIsEnableMob(int isEnableMob) {
        this.isEnableMob = isEnableMob;
    }
}