package com.hszsd.webpay.po;

import java.math.BigDecimal;
import java.util.Date;

public class PaymentInterfacePO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_PAYMENT_INTERFACE.INTERFACE_ID
     *
     * @mbggenerated
     */
    private long interfaceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_PAYMENT_INTERFACE.INTERFACE_NAME
     *
     * @mbggenerated
     */
    private String interfaceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_PAYMENT_INTERFACE.INTERFACE_VALUE
     *
     * @mbggenerated
     */
    private String interfaceValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_PAYMENT_INTERFACE.MERCHANT_ID
     *
     * @mbggenerated
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_PAYMENT_INTERFACE.MERCHANT_KEY
     *
     * @mbggenerated
     */
    private String merchantKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_PAYMENT_INTERFACE.RECHARGE_FEE
     *
     * @mbggenerated
     */
    private BigDecimal rechargeFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_PAYMENT_INTERFACE.PAY_URL
     *
     * @mbggenerated
     */
    private String payUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_PAYMENT_INTERFACE.RETURN_URL
     *
     * @mbggenerated
     */
    private String returnUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_PAYMENT_INTERFACE.NOTICE_URL
     *
     * @mbggenerated
     */
    private String noticeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_PAYMENT_INTERFACE.CHARSET
     *
     * @mbggenerated
     */
    private String charset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_PAYMENT_INTERFACE.SIGN_TYPE
     *
     * @mbggenerated
     */
    private String signType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_PAYMENT_INTERFACE.LOGO_URL
     *
     * @mbggenerated
     */
    private String logoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_PAYMENT_INTERFACE.ORDER_BY
     *
     * @mbggenerated
     */
    private int orderBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_PAYMENT_INTERFACE.IS_ENABLE
     *
     * @mbggenerated
     */
    private int isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_PAYMENT_INTERFACE.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_PAYMENT_INTERFACE.CREATE_BY
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_PAYMENT_INTERFACE.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_PAYMENT_INTERFACE.UPDATE_BY
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_PAYMENT_INTERFACE.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_PAYMENT_INTERFACE.INTERFACE_ID
     *
     * @return the value of HSPAY.TB_PAYMENT_INTERFACE.INTERFACE_ID
     *
     * @mbggenerated
     */
    public long getInterfaceId() {
        return interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_PAYMENT_INTERFACE.INTERFACE_ID
     *
     * @param interfaceId the value for HSPAY.TB_PAYMENT_INTERFACE.INTERFACE_ID
     *
     * @mbggenerated
     */
    public void setInterfaceId(long interfaceId) {
        this.interfaceId = interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_PAYMENT_INTERFACE.INTERFACE_NAME
     *
     * @return the value of HSPAY.TB_PAYMENT_INTERFACE.INTERFACE_NAME
     *
     * @mbggenerated
     */
    public String getInterfaceName() {
        return interfaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_PAYMENT_INTERFACE.INTERFACE_NAME
     *
     * @param interfaceName the value for HSPAY.TB_PAYMENT_INTERFACE.INTERFACE_NAME
     *
     * @mbggenerated
     */
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName == null ? null : interfaceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_PAYMENT_INTERFACE.INTERFACE_VALUE
     *
     * @return the value of HSPAY.TB_PAYMENT_INTERFACE.INTERFACE_VALUE
     *
     * @mbggenerated
     */
    public String getInterfaceValue() {
        return interfaceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_PAYMENT_INTERFACE.INTERFACE_VALUE
     *
     * @param interfaceValue the value for HSPAY.TB_PAYMENT_INTERFACE.INTERFACE_VALUE
     *
     * @mbggenerated
     */
    public void setInterfaceValue(String interfaceValue) {
        this.interfaceValue = interfaceValue == null ? null : interfaceValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_PAYMENT_INTERFACE.MERCHANT_ID
     *
     * @return the value of HSPAY.TB_PAYMENT_INTERFACE.MERCHANT_ID
     *
     * @mbggenerated
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_PAYMENT_INTERFACE.MERCHANT_ID
     *
     * @param merchantId the value for HSPAY.TB_PAYMENT_INTERFACE.MERCHANT_ID
     *
     * @mbggenerated
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_PAYMENT_INTERFACE.MERCHANT_KEY
     *
     * @return the value of HSPAY.TB_PAYMENT_INTERFACE.MERCHANT_KEY
     *
     * @mbggenerated
     */
    public String getMerchantKey() {
        return merchantKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_PAYMENT_INTERFACE.MERCHANT_KEY
     *
     * @param merchantKey the value for HSPAY.TB_PAYMENT_INTERFACE.MERCHANT_KEY
     *
     * @mbggenerated
     */
    public void setMerchantKey(String merchantKey) {
        this.merchantKey = merchantKey == null ? null : merchantKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_PAYMENT_INTERFACE.RECHARGE_FEE
     *
     * @return the value of HSPAY.TB_PAYMENT_INTERFACE.RECHARGE_FEE
     *
     * @mbggenerated
     */
    public BigDecimal getRechargeFee() {
        return rechargeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_PAYMENT_INTERFACE.RECHARGE_FEE
     *
     * @param rechargeFee the value for HSPAY.TB_PAYMENT_INTERFACE.RECHARGE_FEE
     *
     * @mbggenerated
     */
    public void setRechargeFee(BigDecimal rechargeFee) {
        this.rechargeFee = rechargeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_PAYMENT_INTERFACE.PAY_URL
     *
     * @return the value of HSPAY.TB_PAYMENT_INTERFACE.PAY_URL
     *
     * @mbggenerated
     */
    public String getPayUrl() {
        return payUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_PAYMENT_INTERFACE.PAY_URL
     *
     * @param payUrl the value for HSPAY.TB_PAYMENT_INTERFACE.PAY_URL
     *
     * @mbggenerated
     */
    public void setPayUrl(String payUrl) {
        this.payUrl = payUrl == null ? null : payUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_PAYMENT_INTERFACE.RETURN_URL
     *
     * @return the value of HSPAY.TB_PAYMENT_INTERFACE.RETURN_URL
     *
     * @mbggenerated
     */
    public String getReturnUrl() {
        return returnUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_PAYMENT_INTERFACE.RETURN_URL
     *
     * @param returnUrl the value for HSPAY.TB_PAYMENT_INTERFACE.RETURN_URL
     *
     * @mbggenerated
     */
    public void setReturnUrl(String returnUrl) {
        this.returnUrl = returnUrl == null ? null : returnUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_PAYMENT_INTERFACE.NOTICE_URL
     *
     * @return the value of HSPAY.TB_PAYMENT_INTERFACE.NOTICE_URL
     *
     * @mbggenerated
     */
    public String getNoticeUrl() {
        return noticeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_PAYMENT_INTERFACE.NOTICE_URL
     *
     * @param noticeUrl the value for HSPAY.TB_PAYMENT_INTERFACE.NOTICE_URL
     *
     * @mbggenerated
     */
    public void setNoticeUrl(String noticeUrl) {
        this.noticeUrl = noticeUrl == null ? null : noticeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_PAYMENT_INTERFACE.CHARSET
     *
     * @return the value of HSPAY.TB_PAYMENT_INTERFACE.CHARSET
     *
     * @mbggenerated
     */
    public String getCharset() {
        return charset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_PAYMENT_INTERFACE.CHARSET
     *
     * @param charset the value for HSPAY.TB_PAYMENT_INTERFACE.CHARSET
     *
     * @mbggenerated
     */
    public void setCharset(String charset) {
        this.charset = charset == null ? null : charset.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_PAYMENT_INTERFACE.SIGN_TYPE
     *
     * @return the value of HSPAY.TB_PAYMENT_INTERFACE.SIGN_TYPE
     *
     * @mbggenerated
     */
    public String getSignType() {
        return signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_PAYMENT_INTERFACE.SIGN_TYPE
     *
     * @param signType the value for HSPAY.TB_PAYMENT_INTERFACE.SIGN_TYPE
     *
     * @mbggenerated
     */
    public void setSignType(String signType) {
        this.signType = signType == null ? null : signType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_PAYMENT_INTERFACE.LOGO_URL
     *
     * @return the value of HSPAY.TB_PAYMENT_INTERFACE.LOGO_URL
     *
     * @mbggenerated
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_PAYMENT_INTERFACE.LOGO_URL
     *
     * @param logoUrl the value for HSPAY.TB_PAYMENT_INTERFACE.LOGO_URL
     *
     * @mbggenerated
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl == null ? null : logoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_PAYMENT_INTERFACE.ORDER_BY
     *
     * @return the value of HSPAY.TB_PAYMENT_INTERFACE.ORDER_BY
     *
     * @mbggenerated
     */
    public int getOrderBy() {
        return orderBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_PAYMENT_INTERFACE.ORDER_BY
     *
     * @param orderBy the value for HSPAY.TB_PAYMENT_INTERFACE.ORDER_BY
     *
     * @mbggenerated
     */
    public void setOrderBy(int orderBy) {
        this.orderBy = orderBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_PAYMENT_INTERFACE.IS_ENABLE
     *
     * @return the value of HSPAY.TB_PAYMENT_INTERFACE.IS_ENABLE
     *
     * @mbggenerated
     */
    public int getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_PAYMENT_INTERFACE.IS_ENABLE
     *
     * @param isEnable the value for HSPAY.TB_PAYMENT_INTERFACE.IS_ENABLE
     *
     * @mbggenerated
     */
    public void setIsEnable(int isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_PAYMENT_INTERFACE.CREATE_DATE
     *
     * @return the value of HSPAY.TB_PAYMENT_INTERFACE.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_PAYMENT_INTERFACE.CREATE_DATE
     *
     * @param createDate the value for HSPAY.TB_PAYMENT_INTERFACE.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_PAYMENT_INTERFACE.CREATE_BY
     *
     * @return the value of HSPAY.TB_PAYMENT_INTERFACE.CREATE_BY
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_PAYMENT_INTERFACE.CREATE_BY
     *
     * @param createBy the value for HSPAY.TB_PAYMENT_INTERFACE.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_PAYMENT_INTERFACE.UPDATE_DATE
     *
     * @return the value of HSPAY.TB_PAYMENT_INTERFACE.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_PAYMENT_INTERFACE.UPDATE_DATE
     *
     * @param updateDate the value for HSPAY.TB_PAYMENT_INTERFACE.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_PAYMENT_INTERFACE.UPDATE_BY
     *
     * @return the value of HSPAY.TB_PAYMENT_INTERFACE.UPDATE_BY
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_PAYMENT_INTERFACE.UPDATE_BY
     *
     * @param updateBy the value for HSPAY.TB_PAYMENT_INTERFACE.UPDATE_BY
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_PAYMENT_INTERFACE.REMARK
     *
     * @return the value of HSPAY.TB_PAYMENT_INTERFACE.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_PAYMENT_INTERFACE.REMARK
     *
     * @param remark the value for HSPAY.TB_PAYMENT_INTERFACE.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}