package com.hszsd.webpay.po;

import java.math.BigDecimal;
import java.util.Date;

public class TradeRecordPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_RECORD_TMP.TRANS_ID
     *
     * @mbggenerated
     */
    private String transId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_RECORD_TMP.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_RECORD_TMP.TO_USER_ID
     *
     * @mbggenerated
     */
    private String toUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_RECORD_TMP.MONEY
     *
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_RECORD_TMP.CREDIT
     *
     * @mbggenerated
     */
    private BigDecimal credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_RECORD_TMP.MOBILE
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_RECORD_TMP.ORDER_ID
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_RECORD_TMP.PRODUCT_NAME
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_RECORD_TMP.SOURCE_CODE
     *
     * @mbggenerated
     */
    private String sourceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_RECORD_TMP.OPERATE_TYPE
     *
     * @mbggenerated
     */
    private int operateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_RECORD_TMP.ORDER_TYPE
     *
     * @mbggenerated
     */
    private int orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_RECORD_TMP.TRADE_STATUS
     *
     * @mbggenerated
     */
    private int tradeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_RECORD_TMP.RETURN_URL
     *
     * @mbggenerated
     */
    private String returnUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_RECORD_TMP.NOTICE_URL
     *
     * @mbggenerated
     */
    private String noticeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_RECORD_TMP.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_RECORD_TMP.CREATE_BY
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_RECORD_TMP.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_RECORD_TMP.UPDATE_BY
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSPAY.TB_TRADE_RECORD_TMP.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_RECORD_TMP.TRANS_ID
     *
     * @return the value of HSPAY.TB_TRADE_RECORD_TMP.TRANS_ID
     *
     * @mbggenerated
     */
    public String getTransId() {
        return transId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_RECORD_TMP.TRANS_ID
     *
     * @param transId the value for HSPAY.TB_TRADE_RECORD_TMP.TRANS_ID
     *
     * @mbggenerated
     */
    public void setTransId(String transId) {
        this.transId = transId == null ? null : transId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_RECORD_TMP.USER_ID
     *
     * @return the value of HSPAY.TB_TRADE_RECORD_TMP.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_RECORD_TMP.USER_ID
     *
     * @param userId the value for HSPAY.TB_TRADE_RECORD_TMP.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_RECORD_TMP.TO_USER_ID
     *
     * @return the value of HSPAY.TB_TRADE_RECORD_TMP.TO_USER_ID
     *
     * @mbggenerated
     */
    public String getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_RECORD_TMP.TO_USER_ID
     *
     * @param toUserId the value for HSPAY.TB_TRADE_RECORD_TMP.TO_USER_ID
     *
     * @mbggenerated
     */
    public void setToUserId(String toUserId) {
        this.toUserId = toUserId == null ? null : toUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_RECORD_TMP.MONEY
     *
     * @return the value of HSPAY.TB_TRADE_RECORD_TMP.MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_RECORD_TMP.MONEY
     *
     * @param money the value for HSPAY.TB_TRADE_RECORD_TMP.MONEY
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_RECORD_TMP.CREDIT
     *
     * @return the value of HSPAY.TB_TRADE_RECORD_TMP.CREDIT
     *
     * @mbggenerated
     */
    public BigDecimal getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_RECORD_TMP.CREDIT
     *
     * @param credit the value for HSPAY.TB_TRADE_RECORD_TMP.CREDIT
     *
     * @mbggenerated
     */
    public void setCredit(BigDecimal credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_RECORD_TMP.MOBILE
     *
     * @return the value of HSPAY.TB_TRADE_RECORD_TMP.MOBILE
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_RECORD_TMP.MOBILE
     *
     * @param mobile the value for HSPAY.TB_TRADE_RECORD_TMP.MOBILE
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_RECORD_TMP.ORDER_ID
     *
     * @return the value of HSPAY.TB_TRADE_RECORD_TMP.ORDER_ID
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_RECORD_TMP.ORDER_ID
     *
     * @param orderId the value for HSPAY.TB_TRADE_RECORD_TMP.ORDER_ID
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_RECORD_TMP.PRODUCT_NAME
     *
     * @return the value of HSPAY.TB_TRADE_RECORD_TMP.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_RECORD_TMP.PRODUCT_NAME
     *
     * @param productName the value for HSPAY.TB_TRADE_RECORD_TMP.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_RECORD_TMP.SOURCE_CODE
     *
     * @return the value of HSPAY.TB_TRADE_RECORD_TMP.SOURCE_CODE
     *
     * @mbggenerated
     */
    public String getSourceCode() {
        return sourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_RECORD_TMP.SOURCE_CODE
     *
     * @param sourceCode the value for HSPAY.TB_TRADE_RECORD_TMP.SOURCE_CODE
     *
     * @mbggenerated
     */
    public void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode == null ? null : sourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_RECORD_TMP.OPERATE_TYPE
     *
     * @return the value of HSPAY.TB_TRADE_RECORD_TMP.OPERATE_TYPE
     *
     * @mbggenerated
     */
    public int getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_RECORD_TMP.OPERATE_TYPE
     *
     * @param operateType the value for HSPAY.TB_TRADE_RECORD_TMP.OPERATE_TYPE
     *
     * @mbggenerated
     */
    public void setOperateType(int operateType) {
        this.operateType = operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_RECORD_TMP.ORDER_TYPE
     *
     * @return the value of HSPAY.TB_TRADE_RECORD_TMP.ORDER_TYPE
     *
     * @mbggenerated
     */
    public int getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_RECORD_TMP.ORDER_TYPE
     *
     * @param orderType the value for HSPAY.TB_TRADE_RECORD_TMP.ORDER_TYPE
     *
     * @mbggenerated
     */
    public void setOrderType(int orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_RECORD_TMP.TRADE_STATUS
     *
     * @return the value of HSPAY.TB_TRADE_RECORD_TMP.TRADE_STATUS
     *
     * @mbggenerated
     */
    public int getTradeStatus() {
        return tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_RECORD_TMP.TRADE_STATUS
     *
     * @param tradeStatus the value for HSPAY.TB_TRADE_RECORD_TMP.TRADE_STATUS
     *
     * @mbggenerated
     */
    public void setTradeStatus(int tradeStatus) {
        this.tradeStatus = tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_RECORD_TMP.RETURN_URL
     *
     * @return the value of HSPAY.TB_TRADE_RECORD_TMP.RETURN_URL
     *
     * @mbggenerated
     */
    public String getReturnUrl() {
        return returnUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_RECORD_TMP.RETURN_URL
     *
     * @param returnUrl the value for HSPAY.TB_TRADE_RECORD_TMP.RETURN_URL
     *
     * @mbggenerated
     */
    public void setReturnUrl(String returnUrl) {
        this.returnUrl = returnUrl == null ? null : returnUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_RECORD_TMP.NOTICE_URL
     *
     * @return the value of HSPAY.TB_TRADE_RECORD_TMP.NOTICE_URL
     *
     * @mbggenerated
     */
    public String getNoticeUrl() {
        return noticeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_RECORD_TMP.NOTICE_URL
     *
     * @param noticeUrl the value for HSPAY.TB_TRADE_RECORD_TMP.NOTICE_URL
     *
     * @mbggenerated
     */
    public void setNoticeUrl(String noticeUrl) {
        this.noticeUrl = noticeUrl == null ? null : noticeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_RECORD_TMP.CREATE_DATE
     *
     * @return the value of HSPAY.TB_TRADE_RECORD_TMP.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_RECORD_TMP.CREATE_DATE
     *
     * @param createDate the value for HSPAY.TB_TRADE_RECORD_TMP.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_RECORD_TMP.CREATE_BY
     *
     * @return the value of HSPAY.TB_TRADE_RECORD_TMP.CREATE_BY
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_RECORD_TMP.CREATE_BY
     *
     * @param createBy the value for HSPAY.TB_TRADE_RECORD_TMP.CREATE_BY
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_RECORD_TMP.UPDATE_DATE
     *
     * @return the value of HSPAY.TB_TRADE_RECORD_TMP.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_RECORD_TMP.UPDATE_DATE
     *
     * @param updateDate the value for HSPAY.TB_TRADE_RECORD_TMP.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_RECORD_TMP.UPDATE_BY
     *
     * @return the value of HSPAY.TB_TRADE_RECORD_TMP.UPDATE_BY
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_RECORD_TMP.UPDATE_BY
     *
     * @param updateBy the value for HSPAY.TB_TRADE_RECORD_TMP.UPDATE_BY
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSPAY.TB_TRADE_RECORD_TMP.REMARK
     *
     * @return the value of HSPAY.TB_TRADE_RECORD_TMP.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSPAY.TB_TRADE_RECORD_TMP.REMARK
     *
     * @param remark the value for HSPAY.TB_TRADE_RECORD_TMP.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}